export type PlaceType = 'mosque' | 'prayer' | 'restaurant' | 'shop';

export interface Place {
  id: string;
  name: string;
  type: PlaceType;
  /** Los lugares comunitarios aprobados pueden venir sin coordenadas:
   *  salen en la lista pero no en el mapa. */
  lat?: number;
  lng?: number;
  city: string;
  address?: string;
  /** true si el dato sale de una página oficial reciente; false si de una guía de terceros. */
  verified: boolean;
  /** Dato útil y corto: planta, sala de mujeres, certificación… */
  notes?: string;
  /** Hora u observación del rezo del viernes, si la publica el lugar. */
  jumuah?: string;
  /** De dónde sale el dato (página oficial). No se muestra; es para revisar. */
  source?: string;
}

/**
 * Lugares de Kansai: 68 (mezquitas, salas de oración, restaurantes y
 * tiendas), investigados el 17/09/2026 contra la web oficial de cada sitio o
 * guías fiables (Halal Gourmet Japan, Halal Navi, turismo de Kioto y Kobe).
 *
 * Criterios:
 * - Solo lugares que siguen abiertos; fuera los cerrados en 2025–2026.
 * - Restaurantes sin alcohol (Honke Tankuma quedó fuera: menú halal
 *   certificado, pero sirve alcohol al resto de clientes).
 * - `verified: true` = página oficial; `false` = guía de terceros, y la app
 *   lo avisa. Coordenadas sin fuente fiable se omiten: el lugar sale en la
 *   lista y no en el mapa, antes que mandar a alguien a un sitio equivocado.
 * - `source` permite volver a comprobar cada entrada.
 */
export const PLACES: Place[] = [
  {
    id: "osaka-ibaraki-mosque",
    name: "Osaka Ibaraki Mosque",
    type: 'mosque',
    lat: 34.83327,
    lng: 135.53255,
    city: "Ibaraki",
    address: "4-6-13 Toyokawa, Ibaraki-shi, Osaka 567-0057",
    verified: true,
    notes: "7 min walk from Toyokawa monorail station. Limited parking",
    source: "http://www.osakamosque.org/contact/",
  },
  {
    id: "hyogo-masjid-jan-academy",
    name: "Hyogo Masjid (Jan Academy)",
    type: 'mosque',
    lat: 34.70303,
    lng: 135.20061,
    city: "Kobe",
    address: "5-3-15 Kamiwaka-dori, Chuo-ku, Kobe, Hyogo 651-0067",
    verified: true,
    notes: "Open 24 hours per VISIT KOBE. ~15 min walk from Sannomiya",
    source: "https://www.feel-kobe.jp/en/muslim-friendly-travel/theme/prayer_spots",
  },
  {
    id: "kobe-muslim-mosque",
    name: "Kobe Muslim Mosque",
    type: 'mosque',
    lat: 34.6961,
    lng: 135.18798,
    city: "Kobe",
    address: "2-25-14 Nakayamate-dori, Chuo-ku, Kobe, Hyogo 650-0004",
    verified: true,
    notes: "Japan's first mosque (1935). ~10 min walk from Motomachi/Sannomiya. Jumuah livestreamed",
    source: "https://www.kobemosque.com/",
  },
  {
    id: "shiga-masjid",
    name: "Shiga Masjid",
    type: 'mosque',
    lat: 35.00635,
    lng: 135.9574,
    city: "Kusatsu",
    address: "3-4-4 Higashiyagura, Kusatsu-shi, Shiga 525-0054",
    verified: false,
    notes: "Established 2018",
    source: "https://halalgourmet.jp/pray/804770",
  },
  {
    id: "kyoto-central-masjid",
    name: "Kyoto Central Masjid",
    type: 'mosque',
    lat: 35.03501,
    lng: 135.78117,
    city: "Kyoto",
    address: "66 Tanaka Minamiokubo-cho, Sakyo-ku, Kyoto 606-8214",
    verified: true,
    notes: "Run by Kyoto Muslim Community. Separate women's floor; halal grocery. No bike parking",
    jumuah: "Two slots: khutbah 12:15 and 12:55",
    source: "https://www.kyotomosque.jp/",
  },
  {
    id: "kyoto-masjid-kyoto-muslim-association",
    name: "Kyoto Masjid (Kyoto Muslim Association)",
    type: 'mosque',
    lat: 35.02178,
    lng: 135.76922,
    city: "Kyoto",
    address: "Riverside Kojinguchi, 92 Miyagaki-cho, Kamigyo-ku, Kyoto 602-0853",
    verified: true,
    notes: "Tue-Sat 12:00-18:00, closed Sun. Very limited wudu; sources differ on floor (1F/B1)",
    jumuah: "12:30, 13:00, 13:30 (men only)",
    source: "https://kyoto.travel/en/muslim/free-spaces-for-muslims-to-perform-prayers/",
  },
  {
    id: "masjid-al-huda",
    name: "Masjid Al-Huda",
    type: 'mosque',
    lat: 34.93339,
    lng: 135.78776,
    city: "Kyoto",
    address: "2-39 Momoyama-cho Izumi, Fushimi-ku, Kyoto 612-8015",
    verified: false,
    notes: "Run by Al-Huda Muslim Association. ~5 min walk from Rokujizo Station",
    source: "https://halalgourmet.jp/pray/249340",
  },
  {
    id: "miki-masjid",
    name: "Miki Masjid",
    type: 'mosque',
    lat: 34.81055,
    lng: 134.99555,
    city: "Miki",
    address: "Iwamiya, Miki-shi, Hyogo 673-0412",
    verified: false,
    notes: "Rural, reachable by car only. Some sources give 134-1 Iwamiya",
    source: "https://halalgourmet.jp/pray/653252",
  },
  {
    id: "nara-masjid-iqra-academy",
    name: "Nara Masjid & Iqra Academy",
    type: 'mosque',
    lat: 34.6683,
    lng: 135.82252,
    city: "Nara",
    address: "2-322-9 Minamikyobate-cho, Nara 630-8141",
    verified: false,
    notes: "Women's room, wudu, parking. 9 min walk from JR Kyobate",
    jumuah: "12:00-13:00 (per Halal Navi, 2026)",
    source: "https://www.halal-navi.com/blog/en/halal-food-nara-2026-area-guide/",
  },
  {
    id: "japan-da-wah-centre-masjid-al-da-wah",
    name: "Japan Da'wah Centre & Masjid Al Da'wah",
    type: 'mosque',
    city: "Osaka",
    address: "3-2-10 Yamanouchi, Sumiyoshi-ku, Osaka 558-0023",
    verified: false,
    notes: "~1 min walk from JR Sugimotocho Station. Coordinates not verified",
    source: "https://masjid4all.com/mosque/japan-dawah-centre-masjid-al-dawah/",
  },
  {
    id: "masjid-istiqlal-osaka",
    name: "Masjid Istiqlal Osaka",
    type: 'mosque',
    lat: 34.65128,
    lng: 135.49555,
    city: "Osaka",
    address: "1-2-10 Nakahiraki, Nishinari-ku, Osaka 557-0022",
    verified: false,
    notes: "Indonesian community mosque; women's space; ~6 min walk from JR Imamiya",
    source: "https://halalgourmet.jp/pray/233378",
  },
  {
    id: "osaka-grand-masjid-osaka-islamic-center",
    name: "Osaka Grand Masjid (Osaka Islamic Center)",
    type: 'mosque',
    city: "Osaka",
    address: "1-10-28 Nakajima, Nishiyodogawa-ku, Osaka",
    verified: false,
    notes: "Tel 06-6477-9862. Coordinates not verified",
    source: "https://www.instagram.com/osaka.islamic.center/",
  },
  {
    id: "osaka-masjid",
    name: "Osaka Masjid",
    type: 'mosque',
    lat: 34.70831,
    lng: 135.4449,
    city: "Osaka",
    address: "4-12-16 Owada, Nishiyodogawa-ku, Osaka 555-0032",
    verified: true,
    notes: "~6 min walk from Chibune Station. Halal restaurants nearby in Owada",
    jumuah: "13:30 (per official site)",
    source: "https://www.osakamasjid.org/",
  },
  {
    id: "islamic-research-center-japan",
    name: "Islamic Research Center Japan",
    type: 'mosque',
    lat: 34.86324,
    lng: 135.7071,
    city: "Yawata",
    address: "Souwa Bldg 4F, 24-8 Yawata, Yawata-shi, Kyoto 614-8075",
    verified: false,
    notes: "4th floor of a building",
    source: "https://halalgourmet.jp/pray/380608",
  },
  {
    id: "kansai-international-airport-t1-prayer-room-3f",
    name: "Kansai International Airport T1 Prayer Room (3F)",
    type: 'prayer',
    lat: 34.43499,
    lng: 135.24108,
    city: "Izumisano",
    address: "Terminal 1, 3F public area, Kansai International Airport, Osaka 549-0001",
    verified: true,
    notes: "Near Korean Air lounge. Separate men/women rooms and wudu. None in Terminal 2",
    source: "https://www.kansai-airport.or.jp/en/service/other/prayer-room",
  },
  {
    id: "kansai-international-airport-t1-prayer-room-gate-area-main-s",
    name: "Kansai International Airport T1 Prayer Room (Gate Area, Main/South)",
    type: 'prayer',
    lat: 34.43481,
    lng: 135.24568,
    city: "Izumisano",
    address: "Terminal 1, 2F international departure gate area (main building), KIX, Osaka 549-0001",
    verified: true,
    notes: "Airside, after security. Men/women separated with wudu",
    source: "https://www.kansai-airport.or.jp/en/service/other/prayer-room",
  },
  {
    id: "kansai-international-airport-t1-prayer-room-gate-area-north-",
    name: "Kansai International Airport T1 Prayer Room (Gate Area, North Wing)",
    type: 'prayer',
    lat: 34.43562,
    lng: 135.24667,
    city: "Izumisano",
    address: "Terminal 1, 2F international departure gate area, North Wing, KIX, Osaka 549-0001",
    verified: true,
    notes: "Airside, after security. Men/women separated with wudu",
    source: "https://www.kansai-airport.or.jp/en/service/other/prayer-room",
  },
  {
    id: "rinku-premium-outlets-prayer-room",
    name: "Rinku Premium Outlets Prayer Room",
    type: 'prayer',
    lat: 34.4079,
    lng: 135.29481,
    city: "Izumisano",
    address: "3-28 Rinku Orai Minami, Izumisano, Osaka 598-0047",
    verified: false,
    notes: "One stop from Kansai Airport",
    source: "https://halalgourmet.jp/pray/884029",
  },
  {
    id: "kicc-kobe-international-community-center-prayer-space",
    name: "KICC Kobe International Community Center Prayer Space",
    type: 'prayer',
    city: "Kobe",
    address: "4F Asta Kunizuka 1 South Bldg, 5-3-1 Udezuka-cho, Nagata-ku, Kobe, Hyogo 653-0036",
    verified: true,
    notes: "Weekdays 10-20, weekends 10-18, closed holidays. Foot-wash tub",
    source: "https://www.feel-kobe.jp/en/muslim-friendly-travel/theme/prayer_spots",
  },
  {
    id: "kamomeria-naka-pier-central-terminal-prayer-space",
    name: "Kamomeria (Naka Pier Central Terminal) Prayer Space",
    type: 'prayer',
    lat: 34.68253,
    lng: 135.18502,
    city: "Kobe",
    address: "7-1 Hatoba-cho, Chuo-ku, Kobe, Hyogo 650-0042",
    verified: true,
    notes: "Weekdays 8:30-20:30, weekends 8:15-21:00. Sink for wudu",
    source: "https://www.feel-kobe.jp/en/muslim-friendly-travel/theme/prayer_spots",
  },
  {
    id: "kobe-airport-prayer-room",
    name: "Kobe Airport Prayer Room",
    type: 'prayer',
    lat: 34.63798,
    lng: 135.22614,
    city: "Kobe",
    address: "Terminal 2, 1F, 1 Kobe Kuko, Chuo-ku, Kobe, Hyogo 650-0048",
    verified: false,
    notes: "Open to all visitors",
    source: "https://www.kairport.co.jp/en/floormap/playerroom",
  },
  {
    id: "rokko-snow-park-prayer-room",
    name: "Rokko Snow Park Prayer Room",
    type: 'prayer',
    lat: 34.76545,
    lng: 135.24225,
    city: "Kobe",
    address: "4512-98 Kitarokko, Rokkosan-cho, Nada-ku, Kobe, Hyogo 657-0101",
    verified: true,
    notes: "Winter season only; in summer (GREENIA) on request. Men/women rooms",
    source: "https://www.feel-kobe.jp/en/muslim-friendly-travel/theme/prayer_spots",
  },
  {
    id: "kyoto-international-community-house-kokoka-prayer-room",
    name: "Kyoto International Community House (kokoka) Prayer Room",
    type: 'prayer',
    lat: 35.01069,
    lng: 135.7875,
    city: "Kyoto",
    address: "2-1 Awataguchi Toriicho, Sakyo-ku, Kyoto 606-8536",
    verified: true,
    notes: "9:00-21:00, closed Mon. Small room (max 5), no reservation",
    source: "https://kyoto.travel/en/muslim/free-spaces-for-muslims-to-perform-prayers/",
  },
  {
    id: "kyoto-museum-of-traditional-crafts-prayer-room",
    name: "Kyoto Museum of Traditional Crafts Prayer Room",
    type: 'prayer',
    lat: 35.01302,
    lng: 135.7809,
    city: "Kyoto",
    address: "Miyako Messe B1F, 9-1 Okazaki Seishoji-cho, Sakyo-ku, Kyoto",
    verified: false,
    source: "https://halalgourmet.jp/pray/910324",
  },
  {
    id: "m-s-kyoto-information-center-prayer-room",
    name: "M's Kyoto Information Center Prayer Room",
    type: 'prayer',
    lat: 34.98741,
    lng: 135.76069,
    city: "Kyoto",
    address: "M's Kyoto Ekimae Bldg 2F, 545 Higashishiokoji-cho, Shimogyo-ku, Kyoto 600-8216",
    verified: false,
    notes: "Near Kyoto Station",
    source: "https://halalgourmet.jp/pray/140959",
  },
  {
    id: "nijo-castle-prayer-space",
    name: "Nijo Castle Prayer Space",
    type: 'prayer',
    lat: 35.01327,
    lng: 135.7509,
    city: "Kyoto",
    address: "541 Nijojo-cho, Nakagyo-ku, Kyoto 604-8301",
    verified: true,
    notes: "8:45-17:00. Ask at the Castle Estate office; admission required",
    source: "https://kyoto.travel/en/muslim/free-spaces-for-muslims-to-perform-prayers/",
  },
  {
    id: "toei-kyoto-studio-park-uzumasa-eigamura-prayer-space",
    name: "Toei Kyoto Studio Park (Uzumasa Eigamura) Prayer Space",
    type: 'prayer',
    lat: 35.01646,
    lng: 135.70821,
    city: "Kyoto",
    address: "10 Uzumasa Higashihachiokacho, Ukyo-ku, Kyoto 616-8586",
    verified: true,
    notes: "Theme park; no reservation needed",
    source: "https://kyoto.travel/en/muslim/free-spaces-for-muslims-to-perform-prayers/",
  },
  {
    id: "kai-nara-prayer-space",
    name: "KAI (Nara) Prayer Space",
    type: 'prayer',
    lat: 34.67822,
    lng: 135.83436,
    city: "Nara",
    address: "12-1 Wakido-cho, Nara 630-8337",
    verified: false,
    source: "https://www.halal-navi.com/blog/en/halal-food-nara-2026-area-guide/",
  },
  {
    id: "nara-city-tourist-information-center-prayer-room-jr-nara-sta",
    name: "Nara City Tourist Information Center Prayer Room (JR Nara Station)",
    type: 'prayer',
    lat: 34.68037,
    lng: 135.81898,
    city: "Nara",
    address: "1 Sanjo Honmachi, Nara 630-8122",
    verified: false,
    notes: "At JR Nara Station. Center open 9:00-21:00",
    source: "https://www.halal-navi.com/blog/en/halal-food-nara-2026-area-guide/",
  },
  {
    id: "namba-city-prayer-room",
    name: "Namba CITY Prayer Room",
    type: 'prayer',
    lat: 34.66374,
    lng: 135.50172,
    city: "Osaka",
    address: "Namba CITY Main Bldg B1F, 5-1-60 Namba, Chuo-ku, Osaka 542-0076",
    verified: false,
    notes: "Get code at B2 info desk. Approx 11:30-20:30; men/women, wudu",
    source: "https://nambacity.com/assets/pdf/en_floorguide.pdf",
  },
  {
    id: "osaka-international-convention-center-prayer-room",
    name: "Osaka International Convention Center Prayer Room",
    type: 'prayer',
    lat: 34.68938,
    lng: 135.48624,
    city: "Osaka",
    address: "5-3-51 Nakanoshima, Kita-ku, Osaka 530-0005",
    verified: false,
    notes: "Wudu and qibla",
    source: "https://halalgourmet.jp/pray/971750",
  },
  {
    id: "osaka-station-city-prayer-room",
    name: "Osaka Station City Prayer Room",
    type: 'prayer',
    lat: 34.70187,
    lng: 135.49644,
    city: "Osaka",
    address: "South Gate Plaza, South Gate Building 1F, 3-1-1 Umeda, Kita-ku, Osaka 530-0001",
    verified: true,
    notes: "Register first at OSC Information, North Gate Bldg 3F. Hours 10-18 (some sources 11-19)",
    source: "https://osakastationcity.com/en/pdf/prayroom.pdf",
  },
  {
    id: "tempozan-marketplace-prayer-room",
    name: "Tempozan Marketplace Prayer Room",
    type: 'prayer',
    lat: 34.65541,
    lng: 135.43,
    city: "Osaka",
    address: "Tempozan Marketplace 3F, 1-1-10 Kaigandori, Minato-ku, Osaka 552-0022",
    verified: false,
    notes: "Near Kaiyukan aquarium. Unlock code from Kaiyukan info center; men/women, wudu",
    source: "https://halalgourmet.jp/pray/171836",
  },
  {
    id: "lalaport-expocity-prayer-room",
    name: "LaLaport EXPOCITY Prayer Room",
    type: 'prayer',
    lat: 34.8054,
    lng: 135.53327,
    city: "Suita",
    address: "LaLaport EXPOCITY 2F Orange side, 2-1 Senri Banpaku Koen, Suita, Osaka",
    verified: true,
    notes: "Ask at Hikari no Hiroba information 1F. Men/women rooms with wudu",
    source: "https://mitsui-shopping-park.com/en/lalaport/expocity/service/chapel.html",
  },
  {
    id: "ali-s-halal-kitchen-kobe",
    name: "Ali's Halal Kitchen (Kobe)",
    type: 'restaurant',
    lat: 34.69877,
    lng: 135.19249,
    city: "Kobe",
    address: "Otsuka Bldg 1F, 1-20-14 Nakayamate-dori, Chuo-ku, Kobe, Hyogo 650-0004",
    verified: false,
    notes: "Pakistani/Indian, Muslim owner, no alcohol",
    source: "https://www.halal-navi.com/blog/en/halal-restaurants-you-should-not-miss-in-kobe/",
  },
  {
    id: "hyogo-shawarma-bakery",
    name: "Hyogo Shawarma & Bakery",
    type: 'restaurant',
    city: "Kobe",
    address: "5-2-1 Hatatsuka-dori, Chuo-ku, Kobe, Hyogo 651-0068",
    verified: true,
    notes: "Listed as halal food by VISIT KOBE; near Kasuganomichi. Coordinates not verified",
    source: "https://www.feel-kobe.jp/en/muslim-friendly-travel/theme/restaurants",
  },
  {
    id: "kobe-shawarma",
    name: "Kobe Shawarma",
    type: 'restaurant',
    city: "Kobe",
    address: "2-25-10 Nakayamate-dori, Chuo-ku, Kobe, Hyogo 650-0003",
    verified: true,
    notes: "Listed as halal food by VISIT KOBE; next to Kobe Mosque. Coordinates not verified",
    source: "https://www.feel-kobe.jp/en/muslim-friendly-travel/theme/restaurants",
  },
  {
    id: "mezban-mosaic-harborland",
    name: "Mezban (Mosaic Harborland)",
    type: 'restaurant',
    city: "Kobe",
    address: "Mosaic 3F, 1-6-1 Higashikawasaki-cho, Chuo-ku, Kobe, Hyogo",
    verified: false,
    notes: "Indian; certified by Osaka Halal Association. Coordinates not verified",
    source: "https://www.halal-navi.com/blog/en/halal-restaurants-you-should-not-miss-in-kobe/",
  },
  {
    id: "naan-inn",
    name: "Naan Inn",
    type: 'restaurant',
    lat: 34.69669,
    lng: 135.18837,
    city: "Kobe",
    address: "1F Taniguchi Bldg, 3-1-2 Yamamoto-dori, Chuo-ku, Kobe, Hyogo 650-0003",
    verified: true,
    notes: "Pakistani/Indian, all halal, 1 min from Kobe Mosque. Closed Mon",
    source: "https://www.feel-kobe.jp/en/muslim-friendly-travel/theme/restaurants",
  },
  {
    id: "tsuki-usagi",
    name: "Tsuki Usagi",
    type: 'restaurant',
    lat: 34.69255,
    lng: 135.19087,
    city: "Kobe",
    address: "8F Grandcoast Bldg, 2-11-5 Kitanagasa-dori, Chuo-ku, Kobe, Hyogo 650-0012",
    verified: true,
    notes: "Halal-certified Kobe beef courses; reserve 2+ days ahead",
    source: "https://www.feel-kobe.jp/en/muslim-friendly-travel/theme/restaurants",
  },
  {
    id: "gyumon-kyoto-station-halal-wagyu-ramen-gyukatsu",
    name: "GYUMON Kyoto Station (Halal Wagyu Ramen & Gyukatsu)",
    type: 'restaurant',
    lat: 34.99001,
    lng: 135.75688,
    city: "Kyoto",
    address: "746-1 Tatsumi-cho, Shimogyo-ku, Kyoto 600-8307",
    verified: false,
    notes: "Certified by Malaysia Halal Corporation, no alcohol; prayer space",
    source: "https://halalgourmet.jp/restaurant/162685",
  },
  {
    id: "gyumon-volcano-kyoto-kawaramachi",
    name: "GYUMON Volcano Kyoto Kawaramachi",
    type: 'restaurant',
    lat: 35.00229,
    lng: 135.76966,
    city: "Kyoto",
    address: "Yanagawa Bldg 1F, 239-1 Ichino-cho, Shimogyo-ku, Kyoto 600-8018",
    verified: false,
    notes: "Halal spicy wagyu ramen; no alcohol; prayer space",
    source: "https://halalgourmet.jp/restaurant/216757",
  },
  {
    id: "halal-ramen-japan-kyoto",
    name: "HALAL RAMEN JAPAN Kyoto",
    type: 'restaurant',
    lat: 35.00786,
    lng: 135.77015,
    city: "Kyoto",
    address: "Kiyamachi BEST Bldg 7F, 71 Daikoku-cho, Nakagyo-ku, Kyoto 604-8031",
    verified: false,
    notes: "Halal certified, no alcohol; prayer space",
    source: "https://halalgourmet.jp/restaurant/949742",
  },
  {
    id: "halal-ramen-ayam-ya-karasuma-kyoto",
    name: "Halal Ramen Ayam-Ya Karasuma Kyoto",
    type: 'restaurant',
    lat: 35.00434,
    lng: 135.7574,
    city: "Kyoto",
    address: "Douka Bldg 1F, 470 Kannondo-cho, Nakagyo-ku, Kyoto 604-8222",
    verified: true,
    notes: "Japan Halal Foundation certified (FPS-108), no alcohol; prayer space",
    source: "https://www.halal-navi.com/blog/en/halal-food-kyoto-2026-kyoto-station-gion-arashiyama/",
  },
  {
    id: "halal-wagyu-ramen-shinjuku-tei-gion-kyoto",
    name: "Halal Wagyu Ramen Shinjuku-tei Gion Kyoto",
    type: 'restaurant',
    lat: 35.00419,
    lng: 135.77687,
    city: "Kyoto",
    address: "Shijo-dori Gion Bldg B1F, 288 Gionmachi Kitagawa, Higashiyama-ku, Kyoto 605-0073",
    verified: true,
    notes: "Halal certified, no pork/alcohol; prayer space",
    source: "https://www.halal-shinjukutei.com/gion-kyoto",
  },
  {
    id: "halal-wagyu-ramen-shinjuku-tei-kiyomizu-kyoto",
    name: "Halal Wagyu Ramen Shinjuku-tei Kiyomizu Kyoto",
    type: 'restaurant',
    lat: 34.9977,
    lng: 135.77811,
    city: "Kyoto",
    address: "148 Hoshino-cho, Higashiyama-ku, Kyoto 605-0853",
    verified: true,
    notes: "Halal certified, no pork/alcohol; prayer space",
    source: "https://www.halal-shinjukutei.com/kiyomizu-store",
  },
  {
    id: "istanbul-saray",
    name: "Istanbul Saray",
    type: 'restaurant',
    lat: 35.00951,
    lng: 135.76945,
    city: "Kyoto",
    address: "Matsuki Bldg 3F, 534-28 Ebisu-cho, Nakagyo-ku, Kyoto 604-8005",
    verified: false,
    notes: "Turkish. Halal certified, Muslim owner. Near Kawaramachi Sanjo",
    source: "https://halalgourmet.jp/restaurant/616873",
  },
  {
    id: "raju-tanbaguchi",
    name: "RAJU Tanbaguchi",
    type: 'restaurant',
    lat: 34.99589,
    lng: 135.74585,
    city: "Kyoto",
    address: "12 Chudoji Mibugawa-cho, Shimogyo-ku, Kyoto 600-8806",
    verified: false,
    notes: "Indian/Nepali. Listed halal certified & Muslim owner; not on Kyoto council's public list",
    source: "https://halalgourmet.jp/restaurant/483269",
  },
  {
    id: "wagyu-sukiyaki-halra-kyoto",
    name: "Wagyu Sukiyaki HALRA Kyoto",
    type: 'restaurant',
    lat: 35.00461,
    lng: 135.77086,
    city: "Kyoto",
    address: "Merge Kiyamachi 1F, 218-2 Nabeya-cho, Nakagyo-ku, Kyoto 604-0961",
    verified: false,
    notes: "Halal certified per Halal Gourmet; no alcohol",
    source: "https://halalgourmet.jp/restaurant/793117",
  },
  {
    id: "yoshiya-arashiyama",
    name: "Yoshiya Arashiyama",
    type: 'restaurant',
    lat: 35.01406,
    lng: 135.67949,
    city: "Kyoto",
    address: "31 Sagatenryuji Tsukurimichi-cho, Ukyo-ku, Kyoto 616-8384",
    verified: true,
    notes: "Kyoto Halal Council certified, no alcohol. Prayer room with wudu (for patrons)",
    source: "https://yoshiya-kyoto.jp/en",
  },
  {
    id: "gyumon-nara-halal-wagyu-ramen-gyukatsu",
    name: "GYUMON Nara (Halal Wagyu Ramen & Gyukatsu)",
    type: 'restaurant',
    lat: 34.68385,
    lng: 135.82678,
    city: "Nara",
    address: "Morita Bldg B1F, 48 Takama-cho, Nara 630-8241",
    verified: false,
    notes: "Certified by Malaysia Halal Corporation, no alcohol; prayer space",
    source: "https://www.halal-navi.com/blog/en/halal-food-nara-2026-area-guide/",
  },
  {
    id: "halal-turkish-kebab-and-ice-cream-nara",
    name: "Halal Turkish Kebab and Ice Cream (Nara)",
    type: 'restaurant',
    lat: 34.68194,
    lng: 135.82886,
    city: "Nara",
    address: "29 Hashimoto-cho, Nara 630-8217",
    verified: false,
    notes: "Muslim owner, no alcohol. On Sanjo-dori",
    source: "https://halalgourmet.jp/restaurant/741557",
  },
  {
    id: "japanese-restaurant-yoshino-wadokoro-yoshino",
    name: "Japanese Restaurant Yoshino (Wadokoro Yoshino)",
    type: 'restaurant',
    lat: 34.68162,
    lng: 135.81863,
    city: "Nara",
    address: "8-1 Sanjo Honmachi, Nara 630-8122",
    verified: false,
    notes: "Halal certified per Halal Gourmet. Near JR Nara Station",
    source: "https://halalgourmet.jp/restaurant/392677",
  },
  {
    id: "ponte-rosso-halal-veg",
    name: "Ponte Rosso Halal & Veg",
    type: 'restaurant',
    lat: 34.68305,
    lng: 135.82808,
    city: "Nara",
    address: "2 Konishi-cho, Nara 630-8226",
    verified: false,
    notes: "Italian; halal meat, halal kitchen; prayer space. Reservation recommended",
    source: "https://halalgourmet.jp/restaurant/354761",
  },
  {
    id: "umemori-sushi-school-main-store",
    name: "Umemori Sushi School (Main Store)",
    type: 'restaurant',
    lat: 34.68711,
    lng: 135.80653,
    city: "Nara",
    address: "221 Hokkeji-cho, Nara 630-8001",
    verified: false,
    notes: "Hands-on sushi class; halal certified; prayer space. Reservation required",
    source: "https://halalgourmet.jp/restaurant/286182",
  },
  {
    id: "ali-s-kitchen-shinsaibashi",
    name: "Ali's Kitchen (Shinsaibashi)",
    type: 'restaurant',
    lat: 34.67481,
    lng: 135.50098,
    city: "Osaka",
    address: "B1F Toresu Bldg, 1-10-12 Shinsaibashi-suji, Chuo-ku, Osaka 542-0085",
    verified: false,
    notes: "Halal certified, Muslim owner, no alcohol/pork; prayer space",
    source: "https://halalgourmet.jp/restaurant/815199",
  },
  {
    id: "bagus-indonesian-kitchen",
    name: "Bagus Indonesian Kitchen",
    type: 'restaurant',
    lat: 34.71139,
    lng: 135.49546,
    city: "Osaka",
    address: "Daini-Toyo Bldg 1F, 1-9-11 Nakatsu, Kita-ku, Osaka 531-0071",
    verified: false,
    notes: "Indonesian. Muslim owner, halal meat",
    source: "https://halalgourmet.jp/restaurant/625373",
  },
  {
    id: "cafe-bintang",
    name: "Cafe BINTANG",
    type: 'restaurant',
    lat: 34.67462,
    lng: 135.50275,
    city: "Osaka",
    address: "1-19-19 Higashi-Shinsaibashi, Chuo-ku, Osaka 542-0083",
    verified: false,
    notes: "Malaysian/SE Asian. Muslim owner, halal meat; prayer space",
    source: "https://halalgourmet.jp/restaurant/479988",
  },
  {
    id: "halal-wagyu-gyukatsu-shinjuku-tei-osaka-umeda",
    name: "Halal Wagyu Gyukatsu Shinjuku-tei Osaka Umeda",
    type: 'restaurant',
    lat: 34.69945,
    lng: 135.50175,
    city: "Osaka",
    address: "Pont Nouveau 7F, 2-5-30 Sonezaki, Kita-ku, Osaka 530-0057",
    verified: false,
    notes: "Halal certified, no alcohol; prayer space",
    source: "https://halalgourmet.jp/restaurant/915204",
  },
  {
    id: "le-marrakech",
    name: "Le Marrakech",
    type: 'restaurant',
    lat: 34.70658,
    lng: 135.48781,
    city: "Osaka",
    address: "1-17-1 Oyodonaka, Kita-ku, Osaka 531-0076",
    verified: false,
    notes: "Moroccan. Muslim owner, no alcohol",
    source: "https://halalgourmet.jp/restaurant/797032",
  },
  {
    id: "nazar-shinsaibashi",
    name: "NAZAR Shinsaibashi",
    type: 'restaurant',
    lat: 34.67206,
    lng: 135.50279,
    city: "Osaka",
    address: "Matsumura Bldg 2F, 1-16-13 Higashi-Shinsaibashi, Chuo-ku, Osaka 542-0083",
    verified: false,
    notes: "Turkish. Halal certified, Muslim owner; prayer space",
    source: "https://halalgourmet.jp/restaurant/339764",
  },
  {
    id: "osaka-halal-restaurant",
    name: "Osaka Halal Restaurant",
    type: 'restaurant',
    lat: 34.70832,
    lng: 135.4449,
    city: "Osaka",
    address: "4-13-2 Owada, Nishiyodogawa-ku, Osaka 555-0032",
    verified: false,
    notes: "Pakistani. Certified to MS1500. ~1 min from Osaka Masjid (coords approximate)",
    source: "https://www.halal-navi.com/blog/en/halal-food-osaka-2026-muslim-travelers-eat-pray-stay/",
  },
  {
    id: "ramen-gyukotsu-king-shin-osaka",
    name: "Ramen Gyukotsu King Shin-Osaka",
    type: 'restaurant',
    lat: 34.7336,
    lng: 135.5,
    city: "Osaka",
    address: "Arde Shin-Osaka 2F, 5-16-1 Nishinakajima, Yodogawa-ku, Osaka",
    verified: false,
    notes: "Halal-certified beef-bone ramen, no alcohol. Inside JR Shin-Osaka station area",
    source: "https://halalgourmet.jp/restaurant/314819",
  },
  {
    id: "shalimar",
    name: "SHALIMAR",
    type: 'restaurant',
    lat: 34.70996,
    lng: 135.49591,
    city: "Osaka",
    address: "Nakatsu Taiei Bldg 2F, 1-5-1 Nakatsu, Kita-ku, Osaka 531-0071",
    verified: false,
    notes: "Pakistani/Indian. Halal certified, Muslim owner",
    source: "https://halalgourmet.jp/restaurant/622578",
  },
  {
    id: "ryotei-jyusouya",
    name: "Ryotei Jyusouya",
    type: 'restaurant',
    lat: 34.6066,
    lng: 135.66833,
    city: "Sango",
    address: "3-27 Shigisan Nishi, Sango-cho, Ikoma-gun, Nara 636-0832",
    verified: false,
    notes: "Japanese; halal certified; prayer space",
    source: "https://halalgourmet.jp/restaurant/199989",
  },
  {
    id: "kobe-halal-food",
    name: "Kobe Halal Food",
    type: 'shop',
    lat: 34.69631,
    lng: 135.18903,
    city: "Kobe",
    address: "Nishizima Bldg 1F, 2-17-3 Nakayamate-dori, Chuo-ku, Kobe, Hyogo 650-0004",
    verified: false,
    notes: "Halal grocery & meat, 2 min walk from Kobe Mosque",
    source: "https://www.halal-navi.com/blog/en/halal-restaurants-you-should-not-miss-in-kobe/",
  },
  {
    id: "kobe-motomachi-tatsuya-halal-kobe-beef",
    name: "Kobe Motomachi Tatsuya (Halal Kobe Beef)",
    type: 'shop',
    lat: 34.68961,
    lng: 135.18873,
    city: "Kobe",
    address: "1-13-19 Motomachi-dori, Chuo-ku, Kobe, Hyogo 650-0022",
    verified: false,
    notes: "Butcher selling halal-certified Kobe beef (frozen, vacuum-packed)",
    source: "https://halal.kobebeef.co.jp/en",
  },
  {
    id: "japaneid-osaka",
    name: "JAPANeid Osaka",
    type: 'shop',
    lat: 34.67276,
    lng: 135.5007,
    city: "Osaka",
    address: "9F, 1-11-1 Minamihorie, Nishi-ku, Osaka 550-0015",
    verified: false,
    notes: "Halal Japanese snacks & souvenirs; prayer space with wudu",
    source: "https://www.halal-navi.com/blog/en/halal-food-osaka-2026-muslim-travelers-eat-pray-stay/",
  },
];
